### ISSUE TITLE
Is data from Tobii Glasses 3 supported?

### ISSUE THREAD

**Issue by worldOfA** [jeffmacinnes/mobileGazeMapping#15]
Hi,

Is data from Tobii Glasses 3 supported?

Best!

**Comment by jeffmacinnes** [comment]
Hi @worldOfA - It's been ~5 years since I've worked with this tool. I'm excited to learn that Tobii has come out with a new version of their mobile glasses, but unfortunately I haven't used them to know if they are compatible with this tool or not. 

In theory, as long as the new version is outputting a video file and pupil coords relative to the video frame, this tool could be modified to work with the new version.

**Comment by worldOfA** [comment]
Thanks for the prompt reply! I can try it out incase Tobii Pro Lab doesn't come through. I believe there are some modifications relating to sync_times of the video and gaze_data for Tobii Glasses 3, otherwise the output should more or less be the same.

**Comment by jeffmacinnes** [comment]
Sounds great! In the `preprocessing` folder you'll see a set of scripts that are all designed to convert the various output formats from the different manufacturers to a standard output. The Tobii script should give a good starting point for working with the new Tobii Glasses 3 (which are hopefully somewhat similar in terms of the output they produce). If you can get a modified version of the preprocessing script to output data in the standardized format, the rest of this tool will work no problem. 

Best of luck! And if you end up with a modified version of a preprocessing script that works for the Glasses 3, feel free to submit as a PR here and I'd be happy to incorporate it into the repo in case anyone else comes across this in the future.
